<a href="https://colab.research.google.com/github/socome/ML_study/blob/master/lab7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [5]:
# training data(70%)
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

# testing data(30%)
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#Correct prediction Test model
prediction = tf.argmax(hypothesis,1)
is_correct = tf.equal(prediction, tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#Launch

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data,Y:y_data})
    print(step, cost_val, W_val)
    
  print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
  print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y:y_test}))
  
 



0 5.0488596 [[-0.52515084 -0.5962798   0.08064748]
 [ 0.6736697   1.2601842  -2.694368  ]
 [ 0.8295075  -0.15744269 -0.26576382]]
1 4.7268457 [[-0.5495527  -0.6093742   0.11814377]
 [ 0.61242354  1.2214378  -2.5943754 ]
 [ 0.7384284  -0.15385853 -0.17826888]]
2 4.405879 [[-0.56309366 -0.6333266   0.15563715]
 [ 0.6081508   1.1257241  -2.4943888 ]
 [ 0.7050806  -0.20799948 -0.09078009]]
3 4.0864034 [[-0.5870783  -0.64682853  0.19312374]
 [ 0.5475536   1.0863485  -2.394416  ]
 [ 0.61672217 -0.20711552 -0.0033056 ]]
4 3.7679238 [[-0.60055107 -0.6708286   0.23059657]
 [ 0.54176825  0.9921894  -2.2944715 ]
 [ 0.5840745  -0.2619      0.08412657]]
5 3.450999 [[-0.62454367 -0.68427664  0.26803723]
 [ 0.47942582  0.95465374 -2.1945934 ]
 [ 0.496211   -0.26136887  0.17145894]]
6 3.1356802 [[-0.63748777 -0.70868987  0.30539453]
 [ 0.47434768  0.8600254  -2.094887  ]
 [ 0.46670192 -0.31885955  0.2584587 ]]
7 2.8236356 [[-0.66174895 -0.721591    0.34255686]
 [ 0.40838346  0.8266879  -1.9955852 ]
 [