In [9]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data
import tensorflow as tf
import numpy as np

filename_queue = tf.train.string_input_producer(
    ['data_01_test_score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)


 # Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

 # collect batches of cvs in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

 # placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

 # Hypothesis
hypothesis = tf.matmul(X, W) + b

 # Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

 # Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

 # Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

 # Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
coord.request_stop()
coord.join(threads)


0 Cost:  4524.2163 
Prediction:
 [[ 85.461784]
 [107.08893 ]
 [103.157166]
 [112.92596 ]
 [ 82.41113 ]
 [ 62.4217  ]
 [ 84.363434]
 [ 62.120995]
 [101.93929 ]
 [ 96.26881 ]]
10 Cost:  8.140946 
Prediction:
 [[151.54369 ]
 [186.51755 ]
 [181.41693 ]
 [198.16083 ]
 [142.98611 ]
 [107.087906]
 [148.16956 ]
 [109.42959 ]
 [176.17693 ]
 [165.04025 ]]
20 Cost:  9.085515 
Prediction:
 [[151.99422]
 [187.0497 ]
 [181.94595]
 [198.7387 ]
 [143.38823]
 [107.38592]
 [148.60725]
 [109.76157]
 [176.67418]
 [165.50377]]
30 Cost:  9.0692425 
Prediction:
 [[152.00076]
 [187.04814]
 [181.94913]
 [198.74384]
 [143.3833 ]
 [107.3838 ]
 [148.61627]
 [109.77574]
 [176.6726 ]
 [165.50522]]
40 Cost:  9.045187 
Prediction:
 [[152.00429]
 [187.04301]
 [181.94876]
 [198.74513]
 [143.37566]
 [107.37966]
 [148.62238]
 [109.78774]
 [176.66768]
 [165.50354]]
50 Cost:  9.021209 
Prediction:
 [[152.0078 ]
 [187.03786]
 [181.9484 ]
 [198.7464 ]
 [143.36801]
 [107.37552]
 [148.62845]
 [109.7997 ]
 [176.66275]
 [165.501

500 Cost:  8.059504 
Prediction:
 [[152.15714 ]
 [186.81831 ]
 [181.93192 ]
 [198.79974 ]
 [143.04245 ]
 [107.19868 ]
 [148.88629 ]
 [110.307335]
 [176.45203 ]
 [165.42847 ]]
510 Cost:  8.040571 
Prediction:
 [[152.1603  ]
 [186.8137  ]
 [181.93158 ]
 [198.80086 ]
 [143.03563 ]
 [107.194954]
 [148.89168 ]
 [110.31797 ]
 [176.4476  ]
 [165.4269  ]]
520 Cost:  8.021721 
Prediction:
 [[152.16342 ]
 [186.80911 ]
 [181.93124 ]
 [198.80197 ]
 [143.0288  ]
 [107.19123 ]
 [148.89706 ]
 [110.328575]
 [176.44318 ]
 [165.42532 ]]
530 Cost:  8.0029745 
Prediction:
 [[152.16655 ]
 [186.80452 ]
 [181.9309  ]
 [198.80309 ]
 [143.022   ]
 [107.18753 ]
 [148.90245 ]
 [110.339165]
 [176.43877 ]
 [165.42377 ]]
540 Cost:  7.9843035 
Prediction:
 [[152.16966]
 [186.79994]
 [181.93054]
 [198.80417]
 [143.01521]
 [107.18383]
 [148.9078 ]
 [110.34971]
 [176.43434]
 [165.4222 ]]
550 Cost:  7.965785 
Prediction:
 [[152.17279]
 [186.79538]
 [181.93024]
 [198.8053 ]
 [143.00847]
 [107.18014]
 [148.91316]
 [110.36

1030 Cost:  7.1794333 
Prediction:
 [[152.31395 ]
 [186.58904 ]
 [181.9153  ]
 [198.85532 ]
 [142.70279 ]
 [107.012886]
 [149.15459 ]
 [110.83556 ]
 [176.23077 ]
 [165.34892 ]]
1040 Cost:  7.1650515 
Prediction:
 [[152.31673 ]
 [186.58499 ]
 [181.91501 ]
 [198.8563  ]
 [142.69681 ]
 [107.009605]
 [149.1593  ]
 [110.84487 ]
 [176.22687 ]
 [165.3475  ]]
1050 Cost:  7.150749 
Prediction:
 [[152.3195  ]
 [186.58098 ]
 [181.91473 ]
 [198.85727 ]
 [142.69084 ]
 [107.006325]
 [149.16402 ]
 [110.85415 ]
 [176.22296 ]
 [165.34607 ]]
1060 Cost:  7.1365013 
Prediction:
 [[152.32227]
 [186.57693]
 [181.91444]
 [198.85825]
 [142.68488]
 [107.00305]
 [149.16873]
 [110.8634 ]
 [176.21906]
 [165.34465]]
1070 Cost:  7.122346 
Prediction:
 [[152.32503 ]
 [186.57292 ]
 [181.91417 ]
 [198.85922 ]
 [142.67892 ]
 [106.999794]
 [149.17342 ]
 [110.872635]
 [176.21516 ]
 [165.34322 ]]
1080 Cost:  7.108237 
Prediction:
 [[152.32776]
 [186.56892]
 [181.91386]
 [198.86018]
 [142.673  ]
 [106.99653]
 [149.17809]
 

1550 Cost:  6.522348 
Prediction:
 [[152.44981 ]
 [186.39137 ]
 [181.90146 ]
 [198.90312 ]
 [142.41022 ]
 [106.851814]
 [149.38509 ]
 [111.28939 ]
 [176.03902 ]
 [165.27792 ]]
1560 Cost:  6.511393 
Prediction:
 [[152.45227]
 [186.38782]
 [181.90121]
 [198.90399]
 [142.40497]
 [106.84891]
 [149.38922]
 [111.29755]
 [176.03555]
 [165.27664]]
1570 Cost:  6.500489 
Prediction:
 [[152.45473]
 [186.38426]
 [181.90099]
 [198.90486]
 [142.3997 ]
 [106.846  ]
 [149.39336]
 [111.30568]
 [176.0321 ]
 [165.27534]]
1580 Cost:  6.4896226 
Prediction:
 [[152.45715]
 [186.3807 ]
 [181.90073]
 [198.90572]
 [142.39447]
 [106.84311]
 [149.39748]
 [111.3138 ]
 [176.02866]
 [165.27405]]
1590 Cost:  6.4788437 
Prediction:
 [[152.4596  ]
 [186.37718 ]
 [181.9005  ]
 [198.90657 ]
 [142.38925 ]
 [106.840225]
 [149.4016  ]
 [111.321884]
 [176.02522 ]
 [165.27275 ]]
1600 Cost:  6.4680915 
Prediction:
 [[152.46204]
 [186.37366]
 [181.90025]
 [198.90741]
 [142.38403]
 [106.83734]
 [149.4057 ]
 [111.32996]
 [176.02