In [4]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt('data_01_test_score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#data 잘 불러왔는지 확인해보기 (정상확인완료)
#print(x_data.shape, x_data, len(x_data))
#print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W= tf.Variable(tf.random_normal([3,1]), name='weight')
b= tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b #matmul = matrix multiply

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X:x_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction\n", hy_val)

        
#Ask my score
print("Your score will be", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))

print("Other scores will be", sess.run(hypothesis, feed_dict={X:[[60,70,110],[90,100,80]]}))

0 Cost: 82936.03 
Prediction
 [[-118.785576]
 [-138.26453 ]
 [-138.45679 ]
 [-151.15778 ]
 [-104.178085]
 [ -77.14962 ]
 [-115.192085]
 [ -88.31844 ]
 [-128.78035 ]
 [-119.89855 ]
 [-109.26398 ]
 [-105.98773 ]
 [-142.49783 ]
 [-117.66078 ]
 [-118.57534 ]
 [-143.74763 ]
 [-115.11468 ]
 [-141.1112  ]
 [-110.21067 ]
 [-139.38425 ]
 [-136.48723 ]
 [-122.74922 ]
 [-134.17842 ]
 [-130.45718 ]
 [-128.2078  ]]
10 Cost: 23.62794 
Prediction
 [[150.08827]
 [184.89381]
 [179.95757]
 [195.62529]
 [142.27733]
 [104.56029]
 [144.39655]
 [104.13795]
 [173.24031]
 [159.85832]
 [140.82945]
 [140.61041]
 [186.46236]
 [155.79309]
 [152.50009]
 [191.16643]
 [145.66731]
 [186.8242 ]
 [150.21033]
 [172.15181]
 [177.12886]
 [157.86382]
 [170.22795]
 [172.71446]
 [162.01836]]
20 Cost: 19.590832 
Prediction
 [[151.94495]
 [187.12169]
 [182.15416]
 [198.02348]
 [143.97063]
 [105.81744]
 [146.20154]
 [105.48999]
 [175.32883]
 [161.80562]
 [142.56128]
 [142.31868]
 [188.72556]
 [157.6657 ]
 [154.35779]
 [193.4731

270 Cost: 17.756495 
Prediction
 [[151.93927]
 [187.0185 ]
 [182.09052]
 [198.09596]
 [143.75096]
 [105.86311]
 [146.49385]
 [106.04234]
 [175.38336]
 [162.16106]
 [142.66847]
 [142.43626]
 [188.51239]
 [157.27864]
 [154.01099]
 [193.31424]
 [147.77568]
 [189.13051]
 [151.41443]
 [174.78545]
 [179.07518]
 [159.643  ]
 [172.62039]
 [174.85855]
 [164.26569]]
280 Cost: 17.688892 
Prediction
 [[151.93872]
 [187.01382]
 [182.08752]
 [198.09813]
 [143.74194]
 [105.86434]
 [146.50464]
 [106.06328]
 [175.38469]
 [162.17387]
 [142.67212]
 [142.44017]
 [188.50371]
 [157.26338]
 [153.9974 ]
 [193.30746]
 [147.78653]
 [189.13132]
 [151.39206]
 [174.80273]
 [179.06664]
 [159.63678]
 [172.63055]
 [174.85973]
 [164.27415]]
290 Cost: 17.621695 
Prediction
 [[151.93819]
 [187.00919]
 [182.08456]
 [198.10028]
 [143.73294]
 [105.86556]
 [146.51541]
 [106.08416]
 [175.38599]
 [162.18663]
 [142.67575]
 [142.44405]
 [188.49504]
 [157.24817]
 [153.9839 ]
 [193.30072]
 [147.79733]
 [189.1321 ]
 [151.36978]
 [

540 Cost: 16.069408 
Prediction
 [[151.92928 ]
 [186.89478 ]
 [182.01472 ]
 [198.15274 ]
 [143.51389 ]
 [105.890274]
 [146.77496 ]
 [106.58765 ]
 [175.41206 ]
 [162.48564 ]
 [142.7629  ]
 [142.53351 ]
 [188.28903 ]
 [156.88564 ]
 [153.66527 ]
 [193.13763 ]
 [148.05684 ]
 [189.14821 ]
 [150.83607 ]
 [175.23685 ]
 [178.85724 ]
 [159.48544 ]
 [172.88443 ]
 [174.88583 ]
 [164.4871  ]]
550 Cost: 16.012123 
Prediction
 [[151.9291 ]
 [186.89029]
 [182.0121 ]
 [198.15479]
 [143.50536]
 [105.89105]
 [146.78499]
 [106.60707]
 [175.41287]
 [162.49686]
 [142.76625]
 [142.5368 ]
 [188.28122]
 [156.87181]
 [153.65326]
 [193.13133]
 [148.0668 ]
 [189.14874]
 [150.81564]
 [175.25294]
 [178.84967]
 [159.48001]
 [172.89383]
 [174.88669]
 [164.49503]]
560 Cost: 15.955192 
Prediction
 [[151.92892 ]
 [186.8858  ]
 [182.00949 ]
 [198.1568  ]
 [143.49686 ]
 [105.891815]
 [146.79498 ]
 [106.626434]
 [175.41367 ]
 [162.508   ]
 [142.76958 ]
 [142.54008 ]
 [188.27342 ]
 [156.85805 ]
 [153.6413  ]
 [193.12503 ]


830 Cost: 14.5414295 
Prediction
 [[151.9283  ]
 [186.7672  ]
 [181.94308 ]
 [198.20988 ]
 [143.27359 ]
 [105.90701 ]
 [147.05438 ]
 [107.129326]
 [175.42874 ]
 [162.78868 ]
 [142.85551 ]
 [142.62091 ]
 [188.07388 ]
 [156.50435 ]
 [153.33792 ]
 [192.96129 ]
 [148.33362 ]
 [189.15944 ]
 [150.26933 ]
 [175.687   ]
 [178.65007 ]
 [159.33833 ]
 [173.14581 ]
 [174.90642 ]
 [164.70842 ]]
840 Cost: 14.493355 
Prediction
 [[151.92844]
 [186.7629 ]
 [181.94078]
 [198.21178]
 [143.26556]
 [105.90738]
 [147.06361]
 [107.14724]
 [175.42908]
 [162.79836]
 [142.85854]
 [142.62363]
 [188.06688]
 [156.4919 ]
 [153.32738]
 [192.95543]
 [148.34273]
 [189.1597 ]
 [150.25072]
 [175.7019 ]
 [178.64339]
 [159.33363]
 [173.15443]
 [174.90698]
 [164.71576]]
850 Cost: 14.445569 
Prediction
 [[151.92857]
 [186.7586 ]
 [181.93848]
 [198.21368]
 [143.25755]
 [105.90774]
 [147.07283]
 [107.16511]
 [175.42941]
 [162.80798]
 [142.86157]
 [142.62634]
 [188.0599 ]
 [156.47949]
 [153.31688]
 [192.9496 ]
 [148.35179]
 [

1130 Cost: 13.217433 
Prediction
 [[151.93604]
 [186.64108]
 [181.8783 ]
 [198.26508]
 [143.03996]
 [105.91304]
 [147.32083]
 [107.64559]
 [175.43317]
 [163.05876]
 [142.94263]
 [142.6953 ]
 [187.8753 ]
 [156.14972]
 [153.04144]
 [192.79233]
 [148.59497]
 [189.164  ]
 [149.73663]
 [176.11774]
 [178.46158]
 [159.20721]
 [173.39404]
 [174.91977]
 [164.92067]]
1140 Cost: 13.177254 
Prediction
 [[151.93643]
 [186.637  ]
 [181.87628]
 [198.26685]
 [143.03242]
 [105.91306]
 [147.32933]
 [107.66207]
 [175.43314]
 [163.06708]
 [142.94539]
 [142.69753]
 [187.86908]
 [156.13855]
 [153.03223]
 [192.7869 ]
 [148.60329]
 [189.16405]
 [149.71976]
 [176.1315 ]
 [178.45572]
 [159.20319]
 [173.40198]
 [174.92007]
 [164.92746]]
1150 Cost: 13.137301 
Prediction
 [[151.93683]
 [186.63289]
 [181.87427]
 [198.26862]
 [143.0249 ]
 [105.91308]
 [147.33781]
 [107.6785 ]
 [175.43307]
 [163.07533]
 [142.94814]
 [142.69974]
 [187.86287]
 [156.12741]
 [153.02306]
 [192.78152]
 [148.61156]
 [189.16408]
 [149.70291]

1410 Cost: 12.177072 
Prediction
 [[151.94974]
 [186.5288 ]
 [181.8253 ]
 [198.31322]
 [142.83496]
 [105.91016]
 [147.55045]
 [108.09027]
 [175.42769]
 [163.27614]
 [143.01672]
 [142.75214]
 [187.70955]
 [155.8514 ]
 [152.79869]
 [192.64604]
 [148.81815]
 [189.16293]
 [149.28384]
 [176.49014]
 [178.30653]
 [159.10165]
 [173.60716]
 [174.92613]
 [165.10455]]
1420 Cost: 12.142974 
Prediction
 [[151.95033]
 [186.52486]
 [181.82355]
 [198.31487]
 [142.82787]
 [105.90993]
 [147.55833]
 [108.10554]
 [175.42734]
 [163.28334]
 [143.01924]
 [142.75397]
 [187.70395]
 [155.8413 ]
 [152.79057]
 [192.64102]
 [148.82576]
 [189.16281]
 [149.26842]
 [176.50294]
 [178.30135]
 [159.09816]
 [173.61447]
 [174.92625]
 [165.11089]]
1430 Cost: 12.109096 
Prediction
 [[151.95091]
 [186.52097]
 [181.82178]
 [198.31653]
 [142.82079]
 [105.90968]
 [147.5662 ]
 [108.12074]
 [175.42699]
 [163.29051]
 [143.02177]
 [142.75578]
 [187.69836]
 [155.8312 ]
 [152.78252]
 [192.636  ]
 [148.83336]
 [189.16269]
 [149.25304]

1680 Cost: 11.323062 
Prediction
 [[151.96771 ]
 [186.42538 ]
 [181.78027 ]
 [198.35672 ]
 [142.64862 ]
 [105.90104 ]
 [147.75583 ]
 [108.487816]
 [175.41518 ]
 [163.45804 ]
 [143.08221 ]
 [142.79706 ]
 [187.56567 ]
 [155.59055 ]
 [152.59198 ]
 [192.51471 ]
 [149.01604 ]
 [189.15793 ]
 [148.88403 ]
 [176.82419 ]
 [178.17387 ]
 [159.01332 ]
 [173.79712 ]
 [174.92766 ]
 [165.2698  ]]
1690 Cost: 11.29391 
Prediction
 [[151.96846]
 [186.42166]
 [181.7787 ]
 [198.35828]
 [142.64192]
 [105.90059]
 [147.76315]
 [108.50197]
 [175.41461]
 [163.46431]
 [143.08453]
 [142.79855]
 [187.56061]
 [155.58134]
 [152.5848 ]
 [192.51001]
 [149.02306]
 [189.15768]
 [148.86987]
 [176.8361 ]
 [178.16925]
 [159.01028]
 [173.80388]
 [174.92764]
 [165.27573]]
1700 Cost: 11.264945 
Prediction
 [[151.96921]
 [186.41792]
 [181.77715]
 [198.35983]
 [142.63525]
 [105.90013]
 [147.77045]
 [108.5161 ]
 [175.41402]
 [163.47055]
 [143.08684]
 [142.80003]
 [187.55557]
 [155.57219]
 [152.57764]
 [192.50533]
 [149.03006]
 

1960 Cost: 10.567549 
Prediction
 [[151.9903  ]
 [186.32321 ]
 [181.73909 ]
 [198.39902 ]
 [142.4666  ]
 [105.886185]
 [147.95345 ]
 [108.870125]
 [175.39618 ]
 [163.62155 ]
 [143.1445  ]
 [142.83482 ]
 [187.43127 ]
 [155.34503 ]
 [152.40265 ]
 [192.38785 ]
 [149.2049  ]
 [189.14935 ]
 [148.50409 ]
 [177.1465  ]
 [178.05179 ]
 [158.93391 ]
 [173.97928 ]
 [174.9253  ]
 [165.42957 ]]
1970 Cost: 10.542744 
Prediction
 [[151.99117 ]
 [186.31966 ]
 [181.73772 ]
 [198.40048 ]
 [142.4603  ]
 [105.88557 ]
 [147.96022 ]
 [108.883255]
 [175.3954  ]
 [163.62697 ]
 [143.1466  ]
 [142.83601 ]
 [187.42671 ]
 [155.3367  ]
 [152.39632 ]
 [192.38347 ]
 [149.21133 ]
 [189.149   ]
 [148.4911  ]
 [177.15756 ]
 [178.04767 ]
 [158.93129 ]
 [173.98552 ]
 [174.92513 ]
 [165.43504 ]]
1980 Cost: 10.51808 
Prediction
 [[151.99203]
 [186.3161 ]
 [181.73634]
 [198.40193]
 [142.45403]
 [105.88495]
 [147.96698]
 [108.89633]
 [175.3946 ]
 [163.63234]
 [143.14873]
 [142.8372 ]
 [187.4222 ]
 [155.3284 ]
 [152.39001]
 [