<a href="https://colab.research.google.com/github/socome/ML_study/blob/master/Lec6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
uploaded = files.upload()

In [11]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
# Y value를 'one.hot ENCODING' 으로 표시
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

#tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)


with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data,Y:y_data})
    if step % 200 ==0:
      print(step, sess.run(cost, feed_dict={X:x_data,Y:y_data}))

  all = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
  print(all, sess.run(tf.argmax(all,1)))
 


0 6.051074
200 0.58180463
400 0.474821
600 0.3803409
800 0.2891925
1000 0.23476692
1200 0.21270588
1400 0.19435313
1600 0.17883363
1800 0.1655395
2000 0.15402864
[[6.4485874e-03 9.9354136e-01 1.0100360e-05]
 [8.3703148e-01 1.4456449e-01 1.8404063e-02]
 [1.1466876e-08 3.4434642e-04 9.9965560e-01]] [1 0 2]
